### ISSUE TITLE
Revert to manual process for `Type: Epic`

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#106]
Turns out this is a mess, these are OR'd not AND'd. 😭 😩 😖

<img width="520" alt="OR" src="https://user-images.githubusercontent.com/134455/218535820-83e78027-7139-4809-ba79-480ece301f8e.png">

This means that all of the [flows](https://app.unito.io/#/dashboard/syncs/project-sync) I thought were separate are in fact in a race condition to "capture" GitHub issues as they're created with the `Type: Epic` label, regardless of the project.

<img width="1152" alt="disabled" src="https://user-images.githubusercontent.com/134455/218536084-9f25d806-6e4b-42a2-b027-5230174ce4cb.png">

I need to bail. This was supposed to be a quick hack to relieve some friction, but it's been two weeks and despite working with Unito support this is not converging on a workable solution. We're gonna have to drop back to manual creation/linking. I've disabled all of the automations, I'll update docs soon and also try to clean everything up here asap.

# To Do 

- [x] delete flows
- [x] modify Notion docs
- [x] remove `Type: Epic` label
- [x] investigate Jira issues created by Unito
- [x] investigate GH issues mangled by Unito

**Comment by chadwhitacre** [comment]
[Here are the issues created by the bot in Jira](https://getsentry.atlassian.net/issues/?jql=reporter%3D%22639b9b2a3c9bcd363977d9d0%22%20order%20by%20created%20DESC).

**Comment by chadwhitacre** [comment]
Alright I think I'm going to leave well enough alone. I skimmed the Jira issues and I tried to get at the GitHub issues (not much luck). I've asked whether folks find `Type: Epic` valuable enough to keep even w/o the automation on it.

**Comment by chadwhitacre** [comment]
I feel like Unito might rear it's ugly head again but for now I'm calling this done and moving on. Three weeks. Blech!
