### ISSUE TITLE
Keep going with Product Area change

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#137]
Follow-up to #126.

- [x] https://github.com/getsentry/eng-pipes/pull/453
- [x] https://github.com/getsentry/action-github-commit/issues/1
- [x] https://github.com/getsentry/sentry/pull/49047
- [x] don't run red when there are no label changes in a product-owners.yml update (nothing added to commit but untracked files present) - dig up where we saw this
    - [x] https://github.com/getsentry/action-github-commit/pull/17
    - [x] https://github.com/getsentry/action-github-commit/pull/19
- [x] Release [v1.1.0](https://github.com/getsentry/action-github-commit/releases/tag/v1.1.0) of `action-github-commit`, bump in `security-as-code`, and re-enable.
    - [x] https://github.com/getsentry/security-as-code/pull/137
    - [x] https://github.com/getsentry/sentry/pull/49265
    - [x] https://github.com/getsentry/sentry-docs/pull/6970
    - [x] https://github.com/getsentry/sentry/pull/49272
- [x] #143

## Dropped from scope

- #145
- #146

**Comment by chadwhitacre** [comment]
> remove all Team and Component labels

I decided to take a self-serve approach to migration, [drafted an email🔒](https://docs.google.com/document/d/1zYEUXIPI7YVy6jbtyZpaMwmAUQs6hGbv_ap7CnkeggY/edit?usp=sharing) announcing that these labels will be deleted in a month and anyone who cares should migrate the ones they care about to a project board.

**Comment by chadwhitacre** [comment]
> I decided to take a self-serve approach to migration

Of course this includes us as many of the Team-labeled tickets should end up in Product Areas on the Issues Customers Care About board. 😅

**Comment by chadwhitacre** [comment]
Split out tickets for Team/Components removal, etc. Linked in description.
