### ISSUE TITLE
Enable JSON comparation of Sentry models

### ISSUE THREAD

**Issue by azaslavsky** [getsentry/team-ospo#155]
Suppose we have an instance of a Sentry model, say `sentry.userrole`. We export it to a file called `first-export.json`. We then import `first-export.json`, and re-export it to a new file called `second-export.json`. How can we reasonably detect that these two instances are representing the same underlying model?

A naive solution would be to simply diff the pretty-printed JSON using a simple diffing algorithm like git's, but this won't work: `sentry.userrole` contains a `date_updated` field which reflects the time that the model was last modified. The act of re-importing the model will cause this field to be updated, resulting in a failure in our comparison, even though the two instances are still "equivalent" in a semantic sense. Any comparison operations we perform on JSONified models will thus need to account for more nuanced relations like this: cases where the very act of exporting/importing alters or otherwise requires modifying the data itself.

Some cases that we've already identified:
- The `date_updated` case mentioned above.
- We should compare, but then scrub, potentially sensitive items like hashed passwords and secret keys, to prevent them from showing up in ex: stack traces.
- A combination of `date_added` and `date_updated`: we want `second_export.date_added` > `first_export.date_added` AND `second_export.date_added` > `first_export.date_updated` AND `second_export.date_updated` >= `second_export.date_added` (in English: the `second_export`'s instance must have been both created and updated after the `first_export`'s, and the `date_updated` on that `second_export` must be greater than or equal to its `date_added`).
- What do we do about `pk`s? If the re-import occurred into a different database, the `pk` on the model may change depending on the existing state of the db. Realistically, we probably want to add another field called `ordinal`, which enumerates the instance's rank among like models when sorted by `pk` (ex: "this is `model: sentry.userrole, ordinal: 2`, meaning it is the second-lowest `pk` among `sentry.userrole` instances included in this export). We may or may not choose to continue exporting `pk`s, but we will not use them for equality comparisons.
```[tasklist]
### Tasks
- [x] Create and test basic diffing comparison flow
- [x] Support date_updated comparator
- [ ] Support sensitive-data scrubbing comparator
- [ ] Support date_added formatting comparator (the ".000" bug)
```
