### ISSUE TITLE
🗣️ Add Team Drilldown in Looker

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/team-ospo#157]
Teams that are really good at engaging with users will be more successful because feedback is priceless. It is the raw material for our product vision. If we don’t engage, feedback dries up, and we build a product our customers don’t find useful.
<img width="960" alt="Screenshot 2023-07-21 at 2 32 21 PM" src="https://github.com/getsentry/team-ospo/assets/25517925/b11a7a8f-881a-4a4a-a9c6-6b1d51796600">

We’ve been reaching 95% issue SLO response time for Support - great! We’ve been at like 80-85% for POs - good! How do we get POs to great? We don’t have good enough data to generate and validate hypotheses. So we want to improve our visibility. We want teams to have a clear idea of the product areas they own, and we want to filter down our GitHub response metrics to track the performance of individual teams. This will help surface data in order to find learning opportunities on what we’re doing well and what we can do better.

## More Code as a Source of Truth
Last quarter we started using the product-owners.yml in security-as-code as a source of truth for defining product owners for product areas. However, it’s not well defined how these product areas map to internal teams.

Each product area will no longer be mapped to product owners, but a team. One team can own multiple product areas. This will clear up any ambiguity on the relationship between product areas and teams. If a product area grows to span multiple teams, it will be broken down into multiple product areas. 

Teams will now be defined in security-as-code and will map to a list of product owners and the slack channel to send notifications to. Sentry repos will also be defined in security-as-code to map to product areas. This enables us to develop visibility into the teams and product areas that are associated with each repo.

Example snippet of future product-owners.yml
```yaml
by_team:
  team-issues:
    product_owners: # populates GitHub teams
      - eran.arkin
      - rachel.wang
      - zpropersi
      - brian.thi
      - scefali
    slack_channel: foo 
  team-dnd:
    product_owners:
      - adam.mckerlie
      - brent.charbonneau
    slack_channel: bar 

by_area:
  "Sign In":
    - "team-enterprise"
  "Issues":
    - "team-issues"

by_repo:
  sentry-javascript: "team-web-sdks"
  relay: "team-ingest"
  self-hosted: "team-ospo"
  sentry-native: "team-processing"
```

## Dashboard Changes
We’ll need to overhaul the 401 dashboard. It will require us to enable filtering the issue response by issues owned by a team instead of all issues. This will allow teams to have a more fine tuned dashboard to track how well they’re doing on issue response, and issues that are slipping through the cracks. 

Weekly Looker scores to publish a team’s response performance to slack will allow teams to keep track of how well they’re doing, and if there’s work to be done to improve. 

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/team-ospo/issues/173
- [ ] https://github.com/getsentry/team-ospo/issues/174
- [x] Milestone 1 Complete
- [ ] https://github.com/getsentry/team-ospo/issues/175
- [x] Milestone 2 Complete
- [ ] https://github.com/getsentry/team-ospo/issues/177
- [ ] https://github.com/getsentry/team-ospo/issues/176
- [x] Milestone 3 Complete
```

## Future work
- [ ] giving incentives for good GH response times

**Comment by hubertdeng123** [comment]
## Weekly Update Aug 7
- [ ] https://github.com/getsentry/security-as-code/pull/307
- [ ] add `by_repo` in security-as-code
- [ ] start automations for syncing security-as-code with eng-pipes

**Comment by hubertdeng123** [comment]
Investigated moving slack team scores to eng-pipes, think I should be able to query data from bigquery to get slack weekly scores into eng-pipes. Testing this locally doesn't seem to be an easy task though.

**Comment by chadwhitacre** [comment]
Notifications are working! 💃 

<img width="834" alt="Screenshot 2023-10-16 at 4 39 04 PM" src="https://github.com/getsentry/team-ospo/assets/134455/7cc5b9e7-a57b-4cbc-8414-898f924f7504">

**Comment by chadwhitacre** [comment]
Weekly reports are also working! 💃 

<img width="574" alt="Screenshot 2023-10-23 at 5 27 22 PM" src="https://github.com/getsentry/team-ospo/assets/134455/3c0fa215-4200-48f7-9ee5-5de90d24ce96">
