### ISSUE TITLE
🗣️ Track Discussions in Looker

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/team-ospo#165]
We have a decent system right now for managing issues in GitHub, but it's missing some things that would give us better information about our GitHub engagement in order to praise successes and address problems. Discussions are where our PM’s are the busiest, asking questions to gather feedback used to develop and drive our product vision. 

## Metrics for Discussions

GitHub gives us [some basic insights](https://github.com/getsentry/sentry/graphs/community?period=last_3_months) but it's not enough. On our own dashboard we track comments across all GitHub issues, but not in discussions. PM’s are losing out, and we have limited visibility into how successful discussions are and whether or not customer engagement there is healthy. 
<img width="394" alt="253065083-d80c3230-dfab-4ec1-993d-c9fb3b003451" src="https://github.com/getsentry/team-ospo/assets/25517925/2725d4f0-6e02-4574-9329-b27d36801424">

Reactions are another way to determine engagement in discussions. Higher number of reactions typically signals questions that are more interesting, questions that the community are interested in engaging in. 

<img width="916" alt="Screenshot 2023-07-21 at 11 01 17 AM" src="https://github.com/getsentry/team-ospo/assets/25517925/04755816-5840-4d00-97c7-308ed4ac5a16">

These metrics will be included in the Looker weekly scores for tracking response time across all teams.

```[tasklist]
### Tasks
- [x] Enable GH webhooks for discussions in eng-pipes and send discussion metrics to BigQuery
- [x] Build out 401 dashboard to include discussions
- [x] Incorporate health for discussions in weekly slack scoreboards
```
### Bonus
- [ ] Track traffic in discussions

**Comment by hubertdeng123** [comment]
Just need to verify that the slack weekly discussion metrics is working as intended, it'll come in next Mon to the OSPO channel.

**Comment by hubertdeng123** [comment]
I do want to find a better way to trigger these pubsub events, maybe it might be nice to develop a slack handler to send specifically to the OSPO channel for these type of things
