### ISSUE TITLE
Programmatically require sentry teams and repos to be well defined in product-owners.yml in security-as-code

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/team-ospo#173]
Let's give more visibility into which teams map to which product areas. This encompasses two main things. First, we want to know which teams should own which product areas. Two, we want to know which teams own which repos. 

```[tasklist]
### Tasks
- [x] Define a `by_team` list in `product-owners.yml`. `by_area` will now map to teams instead of product owners
- [x] Define a `by_repo` list in `product-owners.yml`, mapping repos to teams
- [x] Edit `make_product_owners.py` to work with the above changes
- [x] Add slack channels to `by_team` list in `product-owners.yml`
```
