### ISSUE TITLE
Start tracking GH customer engagement by teams

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/team-ospo#175]
Once eng-pipes is all synced up to `product-owners.yml`, we'll have all the information we need to start sending information to BigQuery on team response times.

```[tasklist]
### Tasks
- [x] For GH time to respond events, we will send team as part of the payload into BigQuery. This can be an entirely new field in the table
- [x] Put up Looker PR to extract the team data to be used in dashboards
- [x] Have a comma-separate string for "Teams" vs. array repr
- [x] Move Teams column to the front
- [ ] Clean up TTR and make sure sort by it desc
```
