### ISSUE TITLE
Enable slack notifications for sdk repos

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/team-ospo#177]
With the repo <-> teams mapping, we can now enable slack notifications for sdk repos in eng-pipes

```[tasklist]
### Tasks
- [x] eng-pipes PR to extract repo from payload, and use it to map to team slack channel defined in `product-owners.yml`
- [x] support both /notify-for-triage and security-as-code channel Id declarations for testing in the self-hosted repo
- [ ] set up handler to get issues from all sdk repos when sending out hourly notifications
- [ ] https://github.com/getsentry/team-ospo/issues/198
- [ ] consolidate product-owners.yml in eng-pipes with github-orgs.yml
```
