### ISSUE TITLE
FY2024 Q4

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#189]
[← Q3](https://github.com/getsentry/team-ospo/issues/110) &middot; **Q4** &middot; [Q1](https://github.com/getsentry/team-ospo/issues/224) →

*Note: Sentry's fiscal year (FY) runs Feb 1 to Jan 31, so we are in FY2024 right now. :)*

-----

# Yes

- [x] #212
- [x] ~https://github.com/getsentry/team-ospo/issues/153~ - we're basically done, depending on HC to get into customer's hands
- [x] ~https://github.com/getsentry/team-ospo/issues/91~ - did not get to this, prioritized relocation
- [x] ~#211~ - did not get to this, prioritized thought leadership ([FOSS Funders](https://fossfunders.com/), [Open Path](https://openpath.chadwhitacre.com/))
- [x] https://github.com/getsentry/sentry/pull/62441
    - was "Time-boxed attempt to fix analytics pipeline (~2 days)"

# Not Yet

- [ ] Improve how we communicate to/from self-hosted instances
  - [ ] Revive self-hosted broadcast system
  - [ ] Unfrobulate self-hosted usage stats
- [ ] https://github.com/getsentry/self-hosted/issues/1763
- [ ] https://github.com/getsentry/snuba/issues/1670
- [ ] https://github.com/getsentry/team-ospo/issues/218
- [ ] https://github.com/getsentry/team-ospo/issues/219

# Maintain

- [x] Ship Self-hosted.
  - [x] https://github.com/getsentry/self-hosted/issues/2476
  - [x] https://github.com/getsentry/self-hosted/issues/2596
  - [x] https://github.com/getsentry/self-hosted/issues/2605
  - [x] https://github.com/getsentry/self-hosted/issues/2579
  - [x] https://github.com/getsentry/self-hosted/issues/2664
  - [x] https://github.com/getsentry/self-hosted/issues/2656
  - [x] https://github.com/getsentry/self-hosted/issues/2738
- [x] Monitor [TTR/TTT](https://sentryio.cloud.looker.com/dashboards/401).
- [x] Track [Quick Wins](https://www.notion.so/sentry/c5250a08da324284a3b4067912ae7772?v=8a625221b0da48568dff7742cb74e8ec).
- [x] Support [Self-hosted users](https://github.com/getsentry/self-hosted/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Support+Request%22).
- [x] Eat our own [dogfood](https://self-hosted.getsentry.net/).
- [x] bump FOSSA CLI version in [`action-enforce-license-compliance`](https://github.com/getsentry/action-enforce-license-compliance)
  - [x] https://github.com/getsentry/action-enforce-license-compliance/pull/22

**Comment by chadwhitacre** [comment]
Quarter is done tomorrow. We shipped FSL and found the bug in our stats. We also basically landed the org relocation project, we had trouble with LA due to holidays and low traffic volume on relocation attempts, we'll get this in front of customers as Hybrid Cloud rolls out to US and then EU.

**Comment by chadwhitacre** [comment]
Quarter was done two days ago. HC bumped further so closing quarter w/o closing #153. 😭

Onward!
