### ISSUE TITLE
Tell our sustainability story

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#231]
- [x] getsentry/team-ospo#233
- [x] getsentry/team-ospo#243
- [x] getsentry/osspledge.com#4
- [x] getsentry/team-ospo#235

**Comment by chadwhitacre** [comment]
Phew! This has gone around the block like 210 times. I thiiiiiiiiinnnnk we're [dialing it in](https://twitter.com/chadwhitacre_/status/1776808622816637225)?

1. Sustainability - [we value user freedom _and_ developer sustainability](https://blog.sentry.io/sentrys-open-source-values/)
   1. Licensing
      1. [**Fair Source**](https://fair.io/) - general movement
      1. [**FSL**](https://fsl.software/) - specific license
   1. Funding
      1. [**FOSS Funders**](https://fossfunders.com/) - low barrier to entry - anyone who gives anything and blogs about it
      1. **OSS Pledge** - higher barrier to entry - recurring program with an amount tied to some objective measure (e.g., revenue, profit, headcount)
      1. [**Software Commons**](https://softwarecommons.com/) - potential future entity with a more active role

**Comment by chadwhitacre** [comment]
I guess I'm still chewing on whether we handle licensing and funding under one brand or two. I thought to go with one brand under Software Commons and that [didn't work](https://github.com/softwarecommons/softwarecommons.com/issues/4#issuecomment-1987156686) (commons is too loaded a term). Would we want to try this under "Fair"? 🤔

Test:

> Fair Source is an evolution of Open Source that elevates developer sustainability to a value on par with user freedom, via two mechanisms: Fair Source licenses, and the Fair Source Pledge.

**Comment by chadwhitacre** [comment]
The reason to try to do them both under one brand is that they both derive from [one set of values](https://blog.sentry.io/sentrys-open-source-values/). The risk is that we confuse people who are generally either thinking of one or the other as relevant to them.

**Comment by chadwhitacre** [comment]
Guidance from internal convo:

> For me: outcome is pledge gets adoption, not that it validates FSL. If there's not a reason to connect the narratives we shouldnt be forcing it. The pledge getting adoption gives us weight, weight gives us power, power lets us do more things. So don't sacrifice the adoption of the pledge by making it confusing naming just to force couple it to the other efforts. There are ways to benefit the other agendas without naming it something confusing, fwiw, like in the PR/etc.  we can always talk about both efforts, or why this is important, and connect it back, etc. But we have to be given a voice to talk about it, so voice is most important.

And:

> FWIW I think they need to be separate ideas that support each other:
>
> **Fair Source:** For companies who want to be open but defend against free-riders. Safe haven for OSS companies, or open-curious cos that never opened up because of the free rider threat (and hopefully if we build enough of a brand around it, companies who never even considered the idea of opening up but now have FOMO). _Small tent we want to grow into a medium-and-growing tent_
>
> **Pledge:** Every single tech company that leverages OSS in a meaningful way (every tech co) should take the Pledge, and be seen as a pariah if they don't. _Biggest tent imaginable_
