### ISSUE TITLE
Audit for forum links in docs and repoint to GitHub Issues

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#27]
Reticketing from https://github.com/getsentry/self-hosted/issues/1239#issuecomment-1007475963. This is a follow-up to getsentry/self-hosted#1151.

### Todo

- [x] https://github.com/getsentry/sentry-docs/pull/5194
- [x] https://github.com/getsentry/develop/pull/670
- [x] https://github.com/getsentry/static-sites/pull/1321 - open.sentry.io
- [ ] `static-sites`

**Comment by chadwhitacre** [comment]
Update: we mothballed the forum globally, a month or two ago.

**Comment by chadwhitacre** [comment]
`static-sites` is more complicated:

- It's in our legal terms can we change those? Past versions? Doubt it. Need to coordinate with Legal.
- We have a link under "Support" on the [pricing page](https://sentry.io/pricing/), plays into ongoing conversations with Support, should coordinate with them on update there.
- Linked right below the fold on https://open.sentry.io/, need to sort out what to do there. Drop? Replace? With what?

**Comment by chadwhitacre** [comment]
> Linked right below the fold on https://open.sentry.io/, need to sort out what to do there. Drop? Replace? With what?

Dropped in https://github.com/getsentry/static-sites/pull/1321.

**Comment by chadwhitacre** [comment]
> It's in our legal terms 

It's not! It was in old versions but it's not in current (2.0.0). 👍
