### ISSUE TITLE
FY2023 Q3 

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#34]
[← Q2](https://github.com/getsentry/team-ospo/issues/33) &middot; **Q3** &middot; [Q4 →](https://github.com/getsentry/team-ospo/issues/40)

------

# Conclusions

We focused on three big projects this quarter: dogfooding, funding, and engagement.

## 1. [Dogfooding](https://github.com/getsentry/team-ospo/issues/36)

Success! 👉 https://self-hosted.getsentry.net/ 👍

1. **Embarrassment-driven development**—it was embarrassing that we were using neither a) Sentry, nor b) self-hosted Sentry. Now we are!
1. Value from (a): We've already fixed [two](https://github.com/getsentry/self-hosted/pull/1732) [issues](https://github.com/getsentry/self-hosted/pull/1733) discovered from this.
1. Value from (b): We crashed due to low disk space. This is the sort of pain our users feel, we're building empathy which improves our support.
3. Here's [the Vanguard post](https://vanguard.getsentry.net/p/cl80jy0aq00430ls6ttzs6u5j).
4. New team came together! 👏 @ethanhs @hubertdeng123

![](https://user-images.githubusercontent.com/134455/198326419-fa1b5634-273c-4202-a260-25af52a56bd6.png)

## 2. [Funding](https://github.com/getsentry/team-ospo/issues/37)

Success! 👉 "[We Just Gave $260,028 to Open Source Maintainers](https://sentry-blog-preview.netlify.app/2022/10/27/we-just-gave-usd260-028-to-open-source-maintainers/)" (preview, publishing today) 👍 

1. **The main story is continuity**: last year we put an industry-leading program in place, this year we ran it again.
1. Grew program by ~70%, in line with our headcount growth.
2. Pilots with two new funding platforms, [Thanks.dev](https://thanks.dev/home) and [StackAid](https://www.stackaid.us/).

![charts](https://user-images.githubusercontent.com/134455/198329184-ff63cc05-cee7-48ee-a5d5-03441d42d443.jpg)

## 3. Engagement

Progress. 👌

1. Started the quarter thinking we would define and get started building tech to support migration.
1. Went through one big meeting with stakeholders and a number of smaller conversations.
1. **Converging on solving with no new tech**, only process changes + training.
1. "Open Source Customer Engagement Reset" Vanguard post in the works for ~next week.

![](https://user-images.githubusercontent.com/134455/198330501-cdb21e09-db4f-45a9-bcd3-4f554f5900a3.png)

# Maintain

- [x] Self-hosted
    - [x] [22.8.0](https://github.com/getsentry/self-hosted/issues/1583)
    - [x] [22.9.0](https://github.com/getsentry/self-hosted/issues/1656)
    - [x] 22.10.0
    - [x] [backlog](https://github.com/getsentry/self-hosted/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)
        - [x] [**SENTRY_URL_PREFIX**](https://github.com/getsentry/self-hosted/issues/1309) is the big one
- [x] TTR/TTT
- [x] FOSSA - back burner, waiting for them to make changes, we'll need to make changes, too
- [x] [Engagement 🌮s](https://www.notion.so/sentry/Taco-Tato-Time-d0f3606dd8ac408b8c6d8a41a2ad5701)
- [x] **[Funding](https://github.com/getsentry/team-ospo/issues/37)** ([last year](https://blog.sentry.io/2021/10/21/we-just-gave-154-999-dollars-and-89-cents-to-open-source-maintainers))

# Build

## Ship Self-hosted

- [x] Self-hosted Sentry Sesh (community meetup)
    - [x] № 1 scheduled for August 3 w/ @BYK @aminvakil
    - [x] ~One additional, open to the public? [DEX](https://sentry.io/events/dex/)?~ Decided on quarterly, scheduled in Discord.
- [x] **Dogfood**—stand up a self-hosted instance in our GCP, send `install.sh` errors to it https://github.com/getsentry/team-ospo/issues/36

## Drive **Engagement**

_"[Move EPD to GitHub?](https://www.notion.so/sentry/Move-EPD-to-GitHub-0382d12bc2ec4a44a8562191f31a69ff)" scrapped for parts, going after highest-value pieces._

- [x] Work with Customer Support to start doing [support on GitHub](https://github.com/getsentry/team-ospo/issues/32).
- [x] Work with PM to keep moving [Product Requirements](https://github.com/getsentry/sentry/discussions/categories/product-spitballin%CA%BC) to GitHub.
    - win: https://github.com/getsentry/sentry/discussions/37083
    - win: https://github.com/getsentry/sentry/discussions/39460
- [x] Work with EPD/GtM to move [Customer Feedback](https://getsentry.atlassian.net/jira/software/c/projects/FEEDBACK/issues) to GitHub.
    - [x] [~~Build a Zendesk integration~~](https://www.zendesk.com/marketplace/apps/support/24475/jira/) decided to focus on what we can do with zero engineering effort
    - [x] [~Build a browser extension 🤑~](https://user-images.githubusercontent.com/134455/181387329-e6b38e88-615d-47df-8b42-afbc9fce639d.png)
    - [x] [~Write/update Notion docs.~](https://www.notion.so/sentry/Customer-Feedback-Here-We-Gooooo-a669a15fc9234c7b81552b62c9120ba2)
    - [x] ~Retrain CS~
    - [x] ~stretch: Retrain CSM/SE~

# Bonus

- [x] support - help out with "free support" project.
- [x] marketing - help with [DEX](https://sentry.io/events/dex/)
- [x] marketing - laid groundwork for a "Future of Open Source: Licensing" event
- [ ] marketing - go to [ATO](https://www.allthingsopen.org/)

# No

- [x] ~Move EPD to GitHub.~
- [x] ~Add segments to 401 viz to better target 🌮s.~
- [x] ~Convert GH Actions → GH App.~
- [x] ~Build out an attribution page.~

**Comment by chadwhitacre** [comment]
Filing these links re: Customer Feedback board:

- https://getsentry.atlassian.net/browse/FEEDBACK-4
- https://github.com/getsentry/sentry/issues/5572
- https://getsentry.atlassian.net/browse/FEEDBACK-672

**Comment by chadwhitacre** [comment]
# August

- [ ] funding - revisit last year, map out this year
- [ ] funding - pay some projects
- [ ] support - clean up discussions
- [ ] support - get Support on GitHub
- [ ] vacation for Chad
- [ ] engagement - [unconfuse bot](https://github.com/getsentry/eng-pipes/pull/307)
- [ ] backlog - [SENTRY_URL_PREFIX](https://github.com/getsentry/self-hosted/issues/1309)
- [ ] SSS № 1

# September

- [ ] funding - pay most projects
- [ ] SSS № 2?
 
# October

- [ ] funding - pay remaining projects
- [ ] funding - blog post

**Comment by chadwhitacre** [comment]
Bi-weekly EPD update:

1. **funding** – had a call with GitHub Sponsors about current state of their offering, goals for this week are to produce a draft allocation and a send an email out to engineering to invite input
2. **dogfooding** – we have a GCP project set up, goal for end of week is to have self-hosted Sentry installed in it
3. **engagement** – kick-off meeting scheduled for next week, some final prep this week for that

**Comment by chadwhitacre** [comment]
> send an email out to engineering to invite input

Too late. Hack week is next week and we don't want conflict with that. For next time I've made a note in Notion that we need to have the vote before hack week. For this year we'll have to run it after and do our best.

**Comment by chadwhitacre** [comment]
Bi-weekly EPD update:

1. **funding** – set back by Hack Week on internal voting => platform spend (learning for next time) - first two of eight foundation invoices are in the hopper
1. **dogfooding** – we have self-hosted Sentry installed in GCP, next milestone is to land the `install.sh` integration, now aiming for end of next week
1. **engagement** – kick-off meeting went well, we agreed on a number of milestones and owners for each, next step is to follow up post-hackweek and make progress - ETA for cutover is early/mid Q4

**Comment by chadwhitacre** [comment]
I made a Notion page to keep track of [historical engagement tacos](https://www.notion.so/sentry/Taco-Tato-Time-d0f3606dd8ac408b8c6d8a41a2ad5701). I also have Quick Wins on the [Bump, Set, Spike](https://www.notion.so/sentry/Bump-Set-Spike-c714618f881b4579b80b703184ebeadb) doc.

**Comment by chadwhitacre** [comment]
I'd like to think about frameworks, like [what Chrome does](https://opencollective.com/chrome). I want to get a list of the top language/frameworks we support in our SDKs and see if we can include them as a group.

https://dotnetfoundation.org/assets/documents/FY23-Sponsorship-Levels.pdf

**Comment by chadwhitacre** [comment]
Bi-weekly EPD update:

1. **funding**—Employee submissions are open for two more days, vote! On track to be ready to publish a blog post at the end of October, will be speaking at [Red Hat's conference](https://www.allthingsopen.org/) Oct 31—Nov 2.
2. **dogfooding**—[PR landed today](https://github.com/getsentry/self-hosted/pull/1679)! In time for the monthly calver release day after tomorrow.
3. **engagement**—Seem to be settling into three tiers for this roll-out: Customer Support, Corporate CSM, Enterprise CSM/SE. Customer Support decided yesterday to make the switch to GitHub ASAP, will work with them and build from there.

**Comment by chadwhitacre** [comment]
Bi-weekly update:

- We shipped a first iteration on **dogfooding** in 22.9.0 and are tweaking based on what we're seeing so far, on track to wrap up with 22.10.0.
- I've arrived at a final **funding** distribution and am working through invoices, on track for late October blog post.
- Customer **feedback** has taken a back seat due esp. to funding. Support is on board, aiming to focus on that the rest of the quarter.

**Comment by chadwhitacre** [comment]
Bi-weekly update:

- **dogfooding** - Done! Moving into maintenance mode.
- **funding** - All invoices are in, doing platform payouts this week and next, on track to publicize at the end of the month (blog post, [ATO](https://2022.allthingsopen.org/) talk)
- **feedback** - Customer Support has shifted from Jira to GitHub, will work with them the rest of the month/quarter and regroup for next quarter on expanding further

**Comment by chadwhitacre** [comment]
Bi-weekly update:

- **dogfooding** - Okay yeah so def [some maintenance](https://github.com/getsentry/team-ospo/issues/61). 😬
- **funding** - Platform payouts are done on GHS and OC, in the hopper for TD and almost in the hopper for SA. Blog post is in rough draft, publish date is Thursday.
- **feedback** - Lots of activity last week with David and CDV, draft vanguard post is circulating with Ian and a few others. Seems to be coming to a head, aiming for a Nov 1 publish date.
