### ISSUE TITLE
Dogfood self-hosted Sentry

### ISSUE THREAD

**Issue by ethanhs** [getsentry/team-ospo#36]
Sentry is great for error monitoring! We should use it to detect errors in our users' own installation runs.

### Round 1

1. Stand up an instance of self-hosted
    - [x] Get cloud instance
      - [x] Figure out auth
        - Email/password 
      - [x] PII policy -- will be bikesheded in PR
      - [x] ~~Slack integration~~ dropping for now because volume is too high atm
2. Integrate sentry-cli into the installer: https://github.com/getsentry/self-hosted/issues/740
    - [x] Add user prompt for permission while installing
    - [x] First: send install log file on failure
    - [x] Fingerprint/group errors
    - [x] Find important failures to catch/things to test
3. Merge [#1679](https://github.com/getsentry/self-hosted/pull/1679) and exercise it by deploying to GCP.

### Round 2

- [x] usage improvements
  - [x] https://github.com/getsentry/team-ospo/issues/46
  - [x] https://github.com/getsentry/self-hosted/pull/1718
  - [x] https://github.com/getsentry/self-hosted/issues/1724
  - [x] https://github.com/getsentry/team-ospo/issues/43
  - [x] Fix up grouping
- [x] devops
  - [x] Back up Postgres
  - [x] https://github.com/getsentry/team-ospo/issues/44
- [x] code quality
  - [x] https://github.com/getsentry/team-ospo/issues/47
  - [x] Document our prod setup (NGINX, TLS, docker, etc)
- [x] https://github.com/getsentry/team-ospo/issues/49
- [x] https://github.com/getsentry/team-ospo/issues/48
- [x] Post to Vanguard
  - [x] Include some wins:
    - [x] https://github.com/getsentry/self-hosted/pull/1732
    - [x] https://github.com/getsentry/self-hosted/pull/1733
    - [x] Include community inclusion

**Comment by ethanhs** [comment]
PR is up: https://github.com/getsentry/self-hosted/pull/1679

Next steps:
 - Bikeshed wording of user prompt
 - Improve stack traces
 - Tests?
 - Work out postgres backup (!)

**Comment by ethanhs** [comment]
Oh and:
- Document setup (NGINX, TLS, docker, etc)

**Comment by ethanhs** [comment]
- Improve sentry-cli to send full log file

**Comment by chadwhitacre** [comment]
> - [x] Bikeshed wording of user prompt

😂

I wasn't getting notifications on this ticket because I was only watching mentions, vs. all in this repo. Fixed now. 👍

**Comment by chadwhitacre** [comment]
> PII policy -- will be bikesheded in PR

Calling this good. We point to the Privacy Policy, which includes [GDPR pointers](https://sentry.io/privacy/#how-to-access-and-control-your-personal-data). I've added notes to our [internal docs](https://www.notion.so/sentry/GDPR-48a950230484438faf0520e548985e45) on GDPR removal process that our new self-hosted instance is in scope.

**Comment by ethanhs** [comment]
Shipped! 🎉 🚀  Thanks @hubertdeng123 and @chadwhitacre !
