### ISSUE TITLE
Run Fund Fest 2023

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#37]
Meta issue | [Notion](https://www.notion.so/sentry/Funding-Open-Source-5ebce9bcb55849ca8e7d9ff61c32a12b) | [Sheet](https://docs.google.com/spreadsheets/d/1JsOkpxC8Zq9FLnZM3QNr423tyzoaNN9O2QlGUa-40Vo/edit#gid=0)

-----------------

- [x] ~kick-off call with Marketing~
- [x] EPD Bi-weekly - warm up EMs/PMs
- [x] check in with AP, see where bi-weekly payment runs are hitting
- [x] finalize foundation splits
- [x] email all vendors to get the ball rolling
- [x] settle on foundation allocations
- [x] get invoices from foundations
    - [x] Apache
    - [x] ~~Django~~ - GHS
    - [x] OpenJS
    - [x] OSI
    - [x] Postgres
    - [x] Python
    - [x] Rust
- [x] get invoice from Outreachy
- [x] update [deps](http://raw.githack.com/getsentry/deps/fy2022/fundable.html)
    - [x] run through deps once, make sure it works as it stands
    - [x] add php
    - [x] add ruby
    - [x] ~~add java?~~
    - [x] ~~add dotnet?~~
    - [x] ~~add cocoa?~~
    - [x] ~~add unity?~~
- [x] run internal voting
     - [x]  kick-off survey via [team@sentry.io](mailto:team@sentry.io) - 
     - [x]  last-call email to [team@sentry.io](mailto:team@sentry.io)
     - [x]  #team-engineering haranguing and #announcements
- [x] finalize allocations across platforms ([GHS](https://github.com/sponsors), [OSC](https://www.oscollective.org/), [TD](https://www.thanks.dev/), [SA](https://www.stackaid.us/))
    - [x] pay special attention to any projects we're paying less or dropping, ensure it's desired
    - [x] think through if we want to support frameworks ([cf.](https://opencollective.com/chrome))
- [x] pay invoices
- [x] distribute funds or otherwise configure platforms
    - [x] GHS
    - [x] OSC
    - [x] TD
    - [x] SA
- [x] publish blog post
    - [x] get on calendar
    - [x] new artwork?
    - [x] include Postgres quote
    - [x] ~mention Huntr.dev~ dropping due to sensitivity around Sullivan verdict 😞
    - [x] notify all partners
- [x] #66
- [x] #65

**Comment by chadwhitacre** [comment]
I had a call with Outreachy today, invoice incoming.

I think I'll get an invoice from PSF because it's more book-keeping for them if we go through PSF.

**Comment by chadwhitacre** [comment]
I requested an order form for GitHub so I can get the invoice going. If I get an invoice dated by September 7 then I should get that paid the week of September 26 so funds are available by Oct 11 when we need them (our balance is used up on Sept 11).

**Comment by chadwhitacre** [comment]
I won't have final platform amounts determined before late September because voting runs through Sept 15. As long as I have enough in GitHub to cover the estimated first month (or two) then it should be fine to do a second invoice to top up the final balance for the year.

**Comment by chadwhitacre** [comment]
For OC it is a simple one-time payment so no need to overworry about having the balance topped up in time for a monthly distribution as on GitHub.

**Comment by chadwhitacre** [comment]
I'd like to think about frameworks, like [what Chrome does](https://opencollective.com/chrome). I want to get a list of the top language/frameworks we support in our SDKs and see if we can include them as a group.

https://dotnetfoundation.org/assets/documents/FY23-Sponsorship-Levels.pdf

**Comment by chadwhitacre** [comment]
TIL https://stackaid.us/, invite requested

**Comment by chadwhitacre** [comment]
to get to distribution:

- [ ] process submissions into usable list w/ counts
- [ ] finalize SDK upstreams (Go?)
- [ ] start fitting together.

**Comment by chadwhitacre** [comment]
Hrm, grouping projects into ecosystems is not going smoothly.

- I've got one-offs for Flutter, .NET, Swift, ...
- I've got projects like [swc](https://opencollective.com/swc) that are written in Rust but are tooling for JS/TS

🤔

**Comment by chadwhitacre** [comment]
I guess the point of grouping is to line up with the ecosystems we depend on the most, which is Python, JS, and Rust. Anything else can get lumped into "other" (last year called this "open source"), would be nice to list the specifics though to demonstrate breadth of diversity. Also since we are users of these tools then something like swc would count for js from our perspective.

**Comment by chadwhitacre** [comment]
New classification for this year: project vs. individual.

**Comment by chadwhitacre** [comment]
What I don't have from the fund fest is something like:

- project we rely on to ship Sentry
- project individual dev relies on daily to be productive on Sentry
- project individual is interested in but doesn't use for Sentry

🤔

**Comment by chadwhitacre** [comment]
First draft done. [Sheet](https://docs.google.com/spreadsheets/d/1JsOkpxC8Zq9FLnZM3QNr423tyzoaNN9O2QlGUa-40Vo/edit?usp=sharing). [Doc](https://docs.google.com/document/d/1j6VoGPxDAMy1ZF49rtjpj_v7PldoAGet8NS_1-h19Ro/edit?usp=sharing).

**Comment by chadwhitacre** [comment]
Distribution finalized. Invoices obtained for OC, TD, SA. Expecting GHS next week. (Still struggling with OpenJS :shrug:).

SA uses a GitHub App.

TD uses API access, I'm considering a separate user account for that. [Setup Jira](https://getsentry.atlassian.net/servicedesk/customer/portal/4/ISD-3499).

**Comment by chadwhitacre** [comment]
OpenJS is in the chute. 👍 That's all of them!

GitHub distributions are done! Scored [a quote tweet](https://twitter.com/github/status/1580289505386369025)! 😁 💃 

Next week:
- Distribute on OC, TD, SA.
- Draft blog post.

**Comment by chadwhitacre** [comment]
OC done, TD I think I'm done, hearing from Ali seems like he's on it. SA I need to make PRs and do a bunch of config.

Blog post is in draft needs a couple hours work.

**Comment by chadwhitacre** [comment]
Oh and I did go for OWASP.

**Comment by chadwhitacre** [comment]
Punchlist for blog post:

- [ ] add shout-outs for TD and SA
- [ ] write conclusion
- [ ] settle down first pass through
- [ ] make postgres quote
- [ ] dig up and link header from DAM
- [ ] produce external sheet with summary and details
- [ ] go through review cycle with Janet and Sarah (others?)

**Comment by chadwhitacre** [comment]
Blog is live: https://twitter.com/getsentry/status/1585743508031565824

Leaving this open, app review scheduled for tomorrow.

**Comment by chadwhitacre** [comment]
Should've timed it better, bulk of traffic was into the US evening, went [on HN](https://news.ycombinator.com/item?id=33366264) overnight and [got dropped](https://hnrankings.info/33366264/) in the morning. 😞

<img width="972" src="https://user-images.githubusercontent.com/134455/198689765-9a65eef9-5e31-48f7-a6bd-ea16b44f3f28.png">

**Comment by chadwhitacre** [comment]
P.S. Confirmed we got modded:

> It was flagged by users and a moderator downweighted it. Funding/foundation stuff usually isn't that interesting (in HN's sense of the word) because there isn't that much to discuss about it other than "yay" and something generic about either the funder or the category being funded. That of course does not mean it isn't worthwhile—it just doesn't usually lead to engaging discussion.

**Comment by chadwhitacre** [comment]
TD and SA accounts finally moved to a low-privilege account (#65). **_Done_**-_done_-done!
