### ISSUE TITLE
Standardize SDK licenses on MIT

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#56]
Our docs say MIT is our standard license for SDKs. Let's make that real. This is coming up now because [a new SDK](https://github.com/getsentry/profiling-node) took a cue from sentry-javascript and ended up with the wrong license.

Here are the SDKs on https://open.sentry.io/structure/ that aren't MIT:

- [x] https://github.com/getsentry/sentry-javascript/pull/5993
- [x] https://github.com/getsentry/sentry-php/pull/1471
- [x] https://github.com/getsentry/sentry-python/pull/1908
- [x] https://github.com/getsentry/sentry-laravel/pull/654
- [x] https://github.com/getsentry/sentry-symfony/pull/697
- [x] sentry-go
    - [x] https://github.com/getsentry/sentry-go/pull/583
    - [x] https://github.com/getsentry/sentry-go/pull/584
    - [x] https://github.com/getsentry/sentry-go/pull/585

┆Issue is synchronized with this [Jira Epic](https://getsentry.atlassian.net/browse/OSPO-94) by [Unito](https://www.unito.io)

**Comment by chadwhitacre** [comment]
Going with [initial pub] for copyright year since that is status quo, in future we should try to get to [initial pub]-[current release] but that requires automation in many projects so out of scope here.

**Comment by Lms24** [comment]
Just saw the [PR](https://github.com/getsentry/sentry-javascript/pull/5993) in the JS repo
@chadwhitacre I suppose we should also change this in the (coming-soon) [unplugin](https://github.com/getsentry/sentry-unplugin)? Just asking b/c it's technically not an SDK but rather something like a utility for sourcemaps upload

**Comment by chadwhitacre** [comment]
@Lms24 Seems reasonable, yes. :)
