### ISSUE TITLE
Get routing and triage above 90%

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/team-ospo#57]
### Goal
We want to drive up the engagement between Sentry employees and the open source community. Today, this impact is measured in our [OSPO dashboard](https://sentryio.cloud.looker.com/dashboards/401). As a company we should strive to have >90% of issues triaged/routed on time. 

<img width="905" alt="Screen Shot 2022-10-21 at 11 58 17 AM" src="https://user-images.githubusercontent.com/25517925/197269812-f7075a13-31d4-4ee3-a828-bc235473f872.png">

### Why are numbers low? What are opportunities to fix this?
1. At Sentry, we use Slack as a primary source of communication, which isn't being utilized enough to address issues in GitHub. Our [current process](https://www.notion.so/sentry/Customer-Support-GitHub-Playbooks-9b0e835da6e24b7da26cf2b4087e87c4#17db69624c7c49e68d02a3103f965570) involves support going in to Github to find the issues needing to be triaged/routed, and then going to a team's channel to ping them to address the issues. Currently, much of the routing/triaging process is done through Github actions, and migrating to eng-pipes could utilize our Sentaur bot to help out.
2. Support is experiencing pain pinging teams for issues, and it's often difficult for them to find the appropriate channel/team to post in.
3. Employees are not receiving notifications on Untriaged issues after an issue has been routed.
4. Slackbot integration for reminding support on issues is lackluster, it would be better to ping their channel whenever an issue that comes in with the `Untriaged` or `Unrouted` labels, and periodically remind their on-call to address.
5. A bug on Github related to ghost labeling has been affecting our dashboard. A support ticket has been filed but their eng team is pretty slow and we shouldn't rely on them.

### How will we measure engagement?
NUMBERS!! Engagement on the OSPO dashboard should increase

### What are the improvements to be made?
- [x] https://github.com/getsentry/team-ospo/issues/71
- [x] https://github.com/getsentry/team-ospo/issues/62
- [x] https://github.com/getsentry/team-ospo/issues/58 (Medium)
- [x] https://github.com/getsentry/team-ospo/issues/41 (Medium)
- [x] https://github.com/getsentry/team-ospo/issues/59 (Medium)
- [x] https://github.com/getsentry/eng-pipes/issues/245 (Medium)

### Punchlist
- [x] https://github.com/getsentry/eng-pipes/issues/375 (stretch)
- [x] https://github.com/getsentry/.github/pull/107
- [x] https://github.com/getsentry/eng-pipes/pull/382
- [x] https://github.com/getsentry/eng-pipes/issues/384
- [x] https://github.com/getsentry/eng-pipes/issues/388
- [x] https://github.com/getsentry/team-ospo/issues/87
- [x] Vanguard post!

### Follow-up

- [ ] https://github.com/getsentry/team-ospo/issues/60
- [ ] https://github.com/getsentry/team-ospo/issues/89
- [x] https://github.com/getsentry/eng-pipes/issues/385

**Comment by hubertdeng123** [comment]
## Weekly update Nov21:
Last week:
- Added timeToTriage and timeToRoute in BigQuery
- Routing notifications for support are in prod

This week:
- use `timeToTriage` and `timeToRoute` in  OSPO dashboards as a source of truth for SLO violations

**Comment by hubertdeng123** [comment]
### Weekly Update Nov 28:
Last week:
- merged `timeToTriage` and `timeToRoute` in  OSPO dashboards as a source of truth for SLO violations

This week:
- business hour calculations for timeToTriage and timeToRoute
- allow channels to support multiple offices as timezones

**Comment by hubertdeng123** [comment]
### Weekly Update Dec 5:
Last week:
- allow channels to support multiple offices as timezones
- work on supporting holidays in eng-pipes

This week:
- support business hours in `timeToTriage` and `timeToRoute`
- merge supporting holidays in eng-pipes

**Comment by hubertdeng123** [comment]
### Weekly Update Dec 12:
Last week:
- support business hours in `timeToTriage` and `timeToRoute`
- merge supporting holidays in eng-pipes
- fixed a [bug](https://github.com/getsentry/eng-pipes/pull/364) with holiday logic

This week:
- merge business hour support for `timeToTriage` and `timeToRoute`
- double check looker to ensure logic is as expected

**Comment by hubertdeng123** [comment]
Oof late update, slipped my mind this monday
### Weekly Update Dec 12:
Last week:
- merged lookml PR for using business hours in `timeToTriage` and `timeToRoute`
- put up PR to standardize github actions for issue routing to eng-pipes

This week:
- support business hours in `timeToTriage` and `timeToRoute`
- merge supporting holidays in eng-pipes
- fixed a [bug](https://github.com/getsentry/eng-pipes/pull/364) with holiday logic

**Comment by hubertdeng123** [comment]
### Weekly Update Dec 28:
Last week:
- merged lookml [PR](https://github.com/getsentry/lookml) for using business hours in timeToTriage and timeToRoute
- put up https://github.com/getsentry/eng-pipes/pull/370 to standardize github actions for issue routing to eng-pipes

This week:
- merged https://github.com/getsentry/eng-pipes/pull/370 and subsequent pr https://github.com/getsentry/eng-pipes/pull/373 to add routing to sentry repo
- start working on more regular notifications for triaging

**Comment by hubertdeng123** [comment]
### Weekly Update Jan 4:
Last week:

- merged https://github.com/getsentry/eng-pipes/pull/370 and subsequent pr https://github.com/getsentry/eng-pipes/pull/373 to add routing to sentry repo
- start working on more regular notifications for triaging

This week:
- merge https://github.com/getsentry/eng-pipes/pull/376
- merge https://github.com/getsentry/ops/pull/5857 for moving cloud scheduler triage job to terraform for easier edits, should just be able to edit the schedule of the job to get it to run hourly in the future
- put up PR to support hourly notifications

**Comment by hubertdeng123** [comment]
Yes, we can remove some of those.

**Comment by hubertdeng123** [comment]
### Weekly Update Jan 17:
This week:
- [ ] Draft vanguard post
- [ ] Draft Q1 plan
- [ ] https://github.com/getsentry/eng-pipes/issues/384
- [ ] https://github.com/getsentry/eng-pipes/issues/375

**Comment by hubertdeng123** [comment]
### Weekly Update Jan 24:
This week:
- [ ] https://github.com/getsentry/eng-pipes/issues/388
- [ ] Assist on https://github.com/getsentry/team-ospo/issues/86
- [ ] Look into https://github.com/getsentry/eng-pipes/issues/385

**Comment by chadwhitacre** [comment]
Duuuuuuuuude ...

<img width="776" alt="TTR, TTT" src="https://user-images.githubusercontent.com/134455/215866269-c7f74ab5-1fba-4207-b86d-e804803586e4.png">

**Comment by chadwhitacre** [comment]
@hubertdeng123 Quick! Close the ticket while we're above 90%! 😅

**Comment by hubertdeng123** [comment]
Last punchlist item in 😁

Closing this...
