### ISSUE TITLE
Only use vetted actions

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#6]
Right now we use actions from all over the place. For security, we want to only use actions from vetted sources.

### Todo

- [x] Find all actions we use — [done](https://docs.google.com/document/d/10QONpg2mO_-psjhpHYLRCgPdT9HpmH788Ec-YvlRi4I/edit?usp=sharing)
- [ ] Fork and audit actions from randos
- [ ] Configure GitHub to only allow actions from trusted orgs.

**Comment by chadwhitacre** [comment]
I'm washing my hands of this with https://github.com/getsentry/sentry/pull/37166.
