### ISSUE TITLE
Ship ship dogfooding

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#61]
Follow-up to https://github.com/getsentry/team-ospo/issues/36.

## To Do
- [x] https://github.com/getsentry/team-ospo/issues/54
- [x] https://github.com/getsentry/team-ospo/issues/53
- [x] https://github.com/getsentry/self-hosted/issues/1757
- [x] https://github.com/getsentry/self-hosted/issues/1774
- [x] https://github.com/getsentry/team-ospo/issues/52

**Comment by ethanhs** [comment]
Done! 🎉
