### ISSUE TITLE
Make self-hosted backup/restore work excellently

### ISSUE THREAD

**Issue by ethanhs** [getsentry/team-ospo#88]
Currently, the backup/restore workflow experience is not great, and [users are unhappy about it](https://github.com/getsentry/sentry/issues/36868#issuecomment-1271179598). Backup/restore is best practices for upgrading self-hosted versions, and is particularly important when the postgres version or our DB models change. It is also used for migrating from self-hosted to SaaS. The issue about backup/restore being broken is the most commented open source issue in the Sentry repo, and has as many unique commenters as the most commented issues in the self-hosted repo.

<img width="862" alt="Screen Shot 2023-01-17 at 9 41 24 AM" src="https://user-images.githubusercontent.com/9504279/212972568-06c2aee4-f69f-4044-b624-890a95826cfe.png">

Backup/restore is also important for users that want to migrate to SaaS. To make this experience better, we should

Self-hosted issues:

1. https://github.com/getsentry/sentry/issues/36868
1. https://github.com/getsentry/self-hosted/issues/1918

SaaS related concerns:
1. Make sure the [documented workflow for migrating works](https://docs.sentry.io/product/sentry-basics/migration/)
1. See if we can make the [self-hosted to SaaS migrations we handle](https://www.notion.so/sentry/Self-Hosted-SaaS-Migration-Playbook-295317d384ec43ccb9d456e9080889a2) easier for ourselves

Future possibilities enabled from this ticket:
1. https://github.com/getsentry/self-hosted/issues/1403
1. [One-click SaaS migration](https://www.notion.so/sentry/One-click-SaaS-migration-from-OSS-fc316d16efc545928c38b4031735decc)
1. [Migration from one region to another (e.g. US -> EU)](https://www.notion.so/On-the-Subject-of-Self-Hosted-Migrations-2433c8da9ec14775b144945853294a3e)

Rough task list:
1. [ ] Try following [SaaS migration docs](https://docs.sentry.io/product/sentry-basics/migration/) and [self-hosted backup/restore docs](https://develop.sentry.dev/self-hosted/backup/) and see what breaks. Experiment with changing settings to work different parts of what is backed up.
1. [ ] Write Sentry tests to cover what is currently broken with documented workflows.
1. [ ] Fix backup restore to pass new Sentry tests
1. [ ] Write more extensive tests to cover any edge cases not covered above
1. [ ] Write integration test for self-hosted

┆Issue is synchronized with this [Jira Epic](https://getsentry.atlassian.net/browse/OSPO-93) by [Unito](https://www.unito.io)

**Comment by hubertdeng123** [comment]
closing in favor of https://github.com/getsentry/team-ospo/issues/104
