### ISSUE TITLE
Track follow ups

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/team-ospo#89]
### Are customers happy with our response times?
<p float="left">
  <img width="350" alt="poll-results" src="https://user-images.githubusercontent.com/25517925/213287372-0dcf8a82-e0b2-4f9e-8054-bf78d99dbc9a.png">
  <img width="350" alt="Screen Shot 2023-01-18 at 12 15 16 PM" src="https://user-images.githubusercontent.com/25517925/213285347-8b92dc10-f31f-4015-89be-68fee8757c91.png">
</p>

Well, yes and no. In Q4 2022, we've introduced slack notifications for routing/triage. We've seen how effective this can be, as our routing and triage numbers have gone up. These are our recent numbers
<img width="902" alt="Screenshot 2023-04-24 at 9 01 05 AM" src="https://user-images.githubusercontent.com/25517925/234052380-3dd2dc99-3add-4c8c-80a9-295593623ba7.png">
We've reached all time highs for quarterly numbers, with routing at 97.8% and triaging at 87.8%. 
<p float="left">
  <img width="350" alt="Screenshot 2023-04-19 at 3 44 56 PM" src="https://user-images.githubusercontent.com/25517925/233183412-7ae6b485-1a1f-4165-9a1b-b66eaa569a18.png">
  <img width="350" alt="Screenshot 2023-04-19 at 3 45 00 PM" src="https://user-images.githubusercontent.com/25517925/233183386-5a76f45e-499d-462f-b109-a322f8659b0d.png">
</p>

However, here at the OSPO we've noticed two main issues:

1. First off, **triage numbers haven't risen as much as we've wanted them to**. However, we hope that our [changes](https://github.com/getsentry/team-ospo/issues/90) this quarter in overhauling the routing process to use product owners instead of GitHub teams will boost these numbers up. This is currently ongoing, and we should observe the results of this project starting next quarter.
1. Secondly, **nothing is telling us how to respond to follow ups** after an issue has been triaged. It's not uncommon for issues to go on forgotten after an initial response is received ([example](https://github.com/getsentry/sentry/issues/41999)). So perhaps the system is not quite accurate in determining response times in the form of TTR and TTT. 

### How are we analyzing the problem?

Currently, we have two goals: drive up customer engagement numbers and provide a standard way to handle responses between GitHub users and Sentry product owners. Routing and triaging as it currently exists can be a bit confusing. 

- Only the support team performs routing, while triaging is done by the product owners.
- Routing is only done in the repos `sentry` and `sentry-docs`, while triaging is done in every repo owned by Sentry. Issues that are cross repos are hard to track for teams.
- The only Status labels that are super relevant to us are the `Status: Untriaged` and `Status: Unrouted` labels.
- Nothing is telling us how to respond to follow ups after an issue has been triaged. It's not uncommon for issues to go on forgotten after an initial response is received ([example](https://github.com/getsentry/sentry/issues/41999)).

### How can we fix this?
In Q1 2023, our team has implemented a new [process](https://github.com/getsentry/team-ospo/issues/90) for maintaining EPD team changes and product mappings. Most importantly, each issue that comes in corresponds to a product area (Replays, Crons, Issues, etc). A product owner is then responsible for issues that fall under the product area that they own. The initial automations to replace team labels with product owners have been completed. We want to expand on this automation to allow for product owners to easily determine which issues need actionable items. 

Right now, we have two Status labels that are primarily used for notifications `Status: Unrouted` and `Status: Untriaged`. Many of the other `Status: *` labels are unused, and are not used by automation for any purposes. What we really care about is whether or not someone at Sentry should respond to an issue, or if an issue is waiting for a response from the community. We can consolidate these `Status: *` labels into something simpler and more useful for automation purposes.

These are the new status labels:

**Waiting for: Support** = Support team at Sentry
**Waiting for: Community** = everyone else
**Waiting for: Product Owner** = Sentry members who own parts of the product

#### Waiting for: Support
This status is applied to all issues that are new or need to be rerouted. It will also be applied to issues that Support should be responsible for. Support serves as a overseer for which product areas an issue belongs to. The due date column will be occupied for a route by date. For automation purposes, there are two cases to handle
1. New issue comes in
2. Product Owner manually applies the `Waiting for: Support` status to an issue

#### Waiting for: Community
This status will be applied to issues that have been responded to by product owners. Product owners will manually add the `Waiting for: Community` label once they deem that they need more information from the creator of the issue. We will only apply stalebot to issues that are waiting for community. 

#### Waiting for: Product Owner
This status will be applied to issues that have last been interacted with by a community member. If a community member comments to an issue, the status of the issue will become this. 

We want to use these statuses instead of labels as a source of truth to send slack notifications. Furthermore, instead of tracking the success of two different processes (routing and triage), we can instead track the success of overall response time.

### Rough Task List
- [x] https://github.com/getsentry/team-ospo/issues/95
- [x] https://github.com/getsentry/team-ospo/issues/134
- [x] https://github.com/getsentry/team-ospo/issues/138
- [x] https://github.com/getsentry/team-ospo/issues/97
- [x] https://github.com/getsentry/team-ospo/issues/98
- [x] https://github.com/getsentry/team-ospo/issues/133
- [x] https://github.com/getsentry/team-ospo/issues/139
- [x] https://github.com/getsentry/team-ospo/issues/135
- [x] https://github.com/getsentry/eng-pipes/pull/527
- [x] shipped [post](https://vanguard.getsentry.net/p/clkk9bcxb004ms60lyapf0vnm)!

### Bonus
- [ ] Upon closing an issue or clearing label, clear the status of the issue in Issues Someone Else Cares About project
- [ ] Do not mark issues that are created as contractors waiting for product owner
- [ ] Bring back the 👍 and comments
- [ ] https://github.com/getsentry/team-ospo/issues/148
- [ ] For SDK repo, automatically apply a corresponding product area field (sentry-javascript -> SDKS - Web Frontend)
- [ ] Community member comments, then deletes the comment. What do we do?

**Comment by chadwhitacre** [comment]
Something to consider here: in #86 we're realizing that GTM folks should be classed as "community" (basically) even though they're on staff.

**Comment by hubertdeng123** [comment]
## Weekly Update May 8
- [ ] merge https://github.com/getsentry/eng-pipes/pull/446
- [ ] merge https://github.com/getsentry/eng-pipes/pull/451

**Comment by hubertdeng123** [comment]
## Weekly Update May 15
- [ ] Put up PR to add due by timestamps to Looker for `Waiting for: *` labels

**Comment by hubertdeng123** [comment]
## Weekly Update May 22
- [ ] Put up PR to update product area field of Issues Someone Else Cares About project to align with Product Area Label
- [ ] Put up PR to use eng-pipes to add issues to Issues Someone Else Cares About project

**Comment by hubertdeng123** [comment]
## Weekly Update May 30
- [ ] https://github.com/getsentry/eng-pipes/pull/460 (Still working through this, decided to add the functionality of syncing product area labels with product area field on the project
- [ ] https://github.com/getsentry/eng-pipes/pull/461

**Comment by hubertdeng123** [comment]
## Weekly Update June 5
- [ ] sync status field on Issues Someone Else Cares About project with `Waiting for: *` labels
- [ ] don't retriage issues when issues are routed to new product area
- [ ] add contractor support for `Waiting for: *` labels

**Comment by hubertdeng123** [comment]
## Weekly Update June 12

- [ ] https://github.com/getsentry/eng-pipes/pull/480
- [ ] Switch to sending notifications based on `Waiting for: Product Owner` label

**Comment by hubertdeng123** [comment]
## Weekly Update June 20

Need to get the below merged
- [ ] https://github.com/getsentry/eng-pipes/pull/492
- [ ] https://github.com/getsentry/eng-pipes/pull/488

- [ ] put up PR in Looker to use `Waiting for: *` labels to start calculating metrics

**Comment by hubertdeng123** [comment]
## Weekly Update June 26
- [ ] put up PR in Looker to use `Waiting for: *` labels to start calculating metrics

**Comment by hubertdeng123** [comment]
## Weekly Update Jul 5
Short week!
- [ ] https://github.com/getsentry/eng-pipes/pull/506

**Comment by hubertdeng123** [comment]
## Weekly Update Jul 10

- [ ] https://github.com/getsentry/eng-pipes/pull/517
- [ ] Roll out stalebot to all Sentry repos
- [ ] remove status labels

**Comment by hubertdeng123** [comment]
## Weekly Update Jul 17

- [ ] remove status labels
- [ ] Add `Waiting for: Product Owner` on all issues external members comment on

**Comment by chadwhitacre** [comment]
We're ready to close this out, yes?

**Comment by hubertdeng123** [comment]
Tasks are done, just looking to write a shipped post before closing

**Comment by hubertdeng123** [comment]
## Weekly Update Jul 24
- [ ] shipped post
- [ ] Upon closing an issue or clearing label, clear the status of the issue in Issues Someone Else Cares About project
- [ ] Do not mark issues that are created as contractors waiting for product owner

**Comment by hubertdeng123** [comment]
shipped post out! closing this, other items will be bonus

https://vanguard.getsentry.net/p/clkk9bcxb004ms60lyapf0vnm
