### ISSUE TITLE
Better integrate self-hosted into our software development process

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#91]
Self-hosted installations account for [approximately 10% of the ~85,000 organizations we count as Sentry users](https://sentryio.cloud.looker.com/dashboards/217), and, increasingly, these are [a source of major new SaaS accounts](https://www.notion.so/Self-Hosted-SaaS-Migration-Playbook-295317d384ec43ccb9d456e9080889a2). Sentry has a commitment to maintaining self-hosted as a usable packaging of Sentry for low-volume and proof-of-concept deployments, as well as a blueprint for high-availability deploys.

Self-hosted sits at the end of Sentry's development [pipeline](https://docs.google.com/presentation/d/1Ok8a2AXxgT6z0IK8IE3nhc3Ib2zBkmgM_6Px6EtulO0/edit#slide=id.g17038c85f1d_0_5):

<img width="712" alt="pipe dream" src="https://user-images.githubusercontent.com/134455/214622237-b1f07b77-bb64-4cf0-a5bf-c7ff5ea541ae.png">

We participate in the Backend and Infrastructure TSCs, but we don't have enough process around ensuring that feature development or operational changes to Sentry make their way into self-hosted in an orderly fashion. This has resulted in [close calls](https://github.com/getsentry/self-hosted/issues/1701#issuecomment-1281385933) and a pile-up of work to digest:

- [x] https://github.com/getsentry/self-hosted/issues/1610
- [x] https://github.com/getsentry/self-hosted/issues/1873
- [x] https://github.com/getsentry/self-hosted/issues/1838
- [x] https://github.com/getsentry/self-hosted/issues/2269
- [x] https://github.com/getsentry/self-hosted/issues/2122
- [x] https://github.com/getsentry/self-hosted/issues/2200
- [x] https://github.com/getsentry/self-hosted/issues/1993
- [x] https://github.com/getsentry/self-hosted/issues/2713
- [x] https://github.com/getsentry/self-hosted/issues/1869
- [ ] https://github.com/getsentry/self-hosted/issues/2174

What's more, the Sandbox is downstream of Self-hosted, and we definitely want new features to land in the Sandbox, probably at GA.

The outputs of this epic are:

- [ ] Alignment with EPD leadership on expectations, [documented in Notion](https://www.notion.so/sentry/Self-hosted-Sentry-bba9e80b32844696a543aac3b5e7b0bd).
- [ ] Training for EMs/ICs.
- [ ] Probably rewrite the test suite in Python (or at least clean it up a lot and comment it).
- [ ] At least one of the above specific work items completed.

In order to kick this off in Q4, we'd like to invest in two areas.
- [ ] https://github.com/getsentry/self-hosted/issues/2528
- [ ] https://github.com/getsentry/self-hosted/issues/2529

┆Issue is synchronized with this [Jira Epic](https://getsentry.atlassian.net/browse/OSPO-90) by [Unito](https://www.unito.io)

**Comment by chadwhitacre** [comment]
Team changes, less bandwidth, need to shed scope to stay afloat. Dropping this from Q1. Likely revisit after [S4S pipeline🔒](https://groups.google.com/a/sentry.io/g/product-updates/c/lcl550_VKfs) changes (promoting to first-class), will aim to follow suit.

**Comment by chadwhitacre** [comment]
We had a suggestion to use one of the headless browsers for integration tests, forget exactly which one was suggested but one of them would be good.

**Comment by BYK** [comment]
>[pptr.dev](https://pptr.dev/)

[playwright.dev](https://playwright.dev/)

**Comment by chadwhitacre** [comment]
Right! GOOG vs. MSFT

**Comment by BYK** [comment]
@chadwhitacre not just that. Puppeteer locks you into Chrome whereas you can test even on Safari with Playwright.

**Comment by prom3theu5** [comment]
Not to mention playwright supports multiple concurrent "pages" or sessions in test runs
Its pretty good :)

**Comment by azaslavsky** [comment]
Paraphrasing a discussion we had offline:

I think we're pretty close to building out a generic turn-key cloud VM that provisions and sets up a fresh cloud instance with self-hosted at a given SHA downloaded installed and ready to go. If we install VSCode server on here, I think we could use VSCode remote to develop/debug on this instance? 3 reasons why I think this is desirable:
1. We use the same architecture for development as our services when they run; no more apple-silicon warnings from docker. Biggest benefit imo.
2. Easy to spin up new instances on command, and keep work isolated. I feel like self-hosted instances develop “cruft” fairly quickly, making a full-restart necessary kinda often. This takes a long time.
4. Multiple dev environments one could easily switch between. These would not collide with one another.

Biggest downside is potential latency (VSCode has been great for remote dev like this in the past for me, but idk), the setup being finicky, and cost.

**Comment by chadwhitacre** [comment]
[Example fail](https://github.com/getsentry/sentry/pull/61329#issuecomment-1851820151). :-/

**Comment by aldy505** [comment]
A few new feature tickets:
- https://github.com/getsentry/self-hosted/issues/2646
- https://github.com/getsentry/self-hosted/issues/2698
