### ISSUE TITLE
Solve license compliance (again)

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/team-ospo#92]
Last year we deployed [FOSSA](https://fossa.com/) to help us manage open source license compliance. However, persistent [stability issues](https://www.notion.so/sentry/INC-187-FOSSA-downtime-blocked-builds-970be74b593541969b73216d2b374112) forced us to turn FOSSA off in August. We need to solve license compliance again, either by turning FOSSA back on (we've been in conversation with them about product improvements to address our concerns) or through some other means.

### To Do

- [x] Confirm that FOSSA's new features address our concerns. - expected by ~Feb 15~ March 1
- [x] Verify all of our repos are license compliant
- [x] Turn FOSSA back on.
    - [x] #121
    - [x] Bump where pinned
        - [x] https://github.com/getsentry/sentry/pull/47860
        - [x] https://github.com/getsentry/getsentry/pull/10320
        - [x] https://github.com/getsentry/snuba/pull/4078
- [x] shipped post

## Punchlist

- https://github.com/getsentry/team-ospo/issues/124

┆Issue is synchronized with this [Jira Epic](https://getsentry.atlassian.net/browse/OSPO-89) by [Unito](https://www.unito.io)

**Comment by chadwhitacre** [comment]
We had a call with FOSSA yesterday. Most of the eng work on their side is done, there's one more small feature we're waiting for (est. next week or two).

**Comment by chadwhitacre** [comment]
FOSSA has shipped everything we we were waiting for!

**Comment by hubertdeng123** [comment]
What feature in particular were we waiting for? 

Found the [fossa-action](https://github.com/fossas/fossa-action/releases/tag/v1.3.1) but it appears that a release hasn't happened in a while there.

Is it the release in the [fossa-cli](https://github.com/fossas/fossa-cli/releases) where Git based dependencies are detected and handled correctly?

**Comment by hubertdeng123** [comment]
Ah probably this one, it looks like the latest release has the changes we want:
https://github.com/fossas/fossa-cli/pull/1165

**Comment by hubertdeng123** [comment]
Notes after investigating FOSSA and the past incidents

1. How will we know if FOSSA api is down? Is there an endpoint to query accurately to determine if FOSSA scanning is down?
2. It seems like fossa-action is using fossa-cli to perform `fossa analyze` and `fossa test`. Will [fossa-action](https://github.com/fossas/fossa-action) properly detect when there is an issue with FOSSA? How will that be surfaced in GitHub?
3. If our GitHub action uses `fossa-cli analyze` and `fossa-cli test` instead, will that return appropriate erroring for Sentry to ignore the CI run? Seeing this change [here](https://github.com/fossas/fossa-cli/pull/1048) but unsure if that applies to just error message or error code.

**Comment by hubertdeng123** [comment]
From FOSSA:

From FOSSA:
> I reached out to our engineering team to give you all the info you need. This is our health endpoint that you can use:
https://app.fossa.com/health

> The FOSSA action (which uses the CLI) will detect/fail on issues, such as not providing a token, providing the right access token (push-only tokens generated by users with the editor/admin role), no available targets to scan, etc. Those are pretty much application level issues that will exit on 1.
FOSSA will exit on non-zero codes for networked related events as well, whether
> - FOSSA is down (maintenance upgrades or w/e reasons)
> - GH action runners went down for some reason
>   - Network between GH and FOSSA is somehow slow/blocking

> If our health check passes, there's no guarantee that the FOSSA scan will then work (after you check) since they're independent events.
We recommend that if you don’t want to gate CI on FOSSA,  either
> - Add continue-on-error: true to the FOSSA action step, or
> - If you run FOSSA manually (using the CLI), you can do  fossa analyze || true in a step
> I'm not sure if you run fossa test afterwards, but if you do I'd place some Actions logic to say if the analysis step failed then bypass the fossa test step.

As such, it seems reasonable to add the `continue-on-error` to the FOSSA action step

**Comment by hubertdeng123** [comment]
## Weekly Update 04/13
- [ ] check in with legal on FOSSA license compliance
- [ ] add Sentry to enforce license compliance action

**Comment by hubertdeng123** [comment]
## Weekly Update 04/24
- [ ] Enable FOSSA across pinned repos (sentry, getsentry, snuba)

**Comment by hubertdeng123** [comment]
done! 🚢

**Comment by chadwhitacre** [comment]
Link the shipped! :)

**Comment by chadwhitacre** [comment]
https://vanguard.getsentry.net/p/clgy6bddv0000s60lkfcxlgha

**Comment by chadwhitacre** [comment]
Heeeeeeeey! 💃  🥔 @hubertdeng123
